#drz custom user files features
DRZ_USE_LONGPRESS = yes
DRZ_USE_MACROS = yes
DRZ_USE_AUTOCORRECTION = yes
DRZ_USE_UNICODE = yes
DRZ_USE_RGBMATRIX = yes
DRZ_USE_WPM = yes

#qmk features
SWAP_HANDS_ENABLE = yes
LEADER_ENABLE = yes
TAPDANCE_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_LOCK_ENABLE = yes

